CREATE VIEW ATLETASERIE
AS SELECT 
    A.CODATLETA,A.NOME,SC.CODSERIE,S.ETAPA,
    SC.RAIAPARTICIPACAO,SC.COLOCACAO,SC.MARCA,
    SC.STATUSCLASSIFICACAOATLETA,S.DATA, S.HORA,
    M.NOME AS MODALIDADE_NOME
FROM ATLETA A
INNER JOIN SERIECLASSIFICACAO SC
ON A.CODATLETA = SC.CODATLETA
INNER JOIN SERIE S
ON SC.CODSERIE = S.CODSERIE
INNER JOIN PROVA P
ON S.CODPROVA = P.CODPROVA
INNER JOIN MODALIDADE M
ON P.CODMODALIDADE = M.CODMODALIDADE;
