DROP TABLE ATLETAHISTORICO CASCADE CONSTRAINTS;
DROP TABLE MODALIDADE CASCADE CONSTRAINTS;
DROP TABLE PROVAINSCRITOS CASCADE CONSTRAINTS;
DROP TABLE SERIE CASCADE CONSTRAINTS;
DROP TABLE SERIECLASSIFICACAO CASCADE CONSTRAINTS;
DROP TABLE TORNEIO CASCADE CONSTRAINTS;  
DROP TABLE ATLETA CASCADE CONSTRAINTS;

DROP SEQUENCE codTorneio;
DROP SEQUENCE codModalidade;
DROP SEQUENCE codProva;
DROP SEQUENCE codSerie;
DROP SEQUENCE codAtleta;