DROP TABLE ATLETAHISTORICO CASCADE CONSTRAINTS;
DROP TABLE MODALIDADE CASCADE CONSTRAINTS;
DROP TABLE PROVAINSCRITOS CASCADE CONSTRAINTS;
DROP TABLE SERIE CASCADE CONSTRAINTS;
DROP TABLE SERIECLASSIFICACAO CASCADE CONSTRAINTS;
DROP TABLE TORNEIO CASCADE CONSTRAINTS;  
DROP TABLE ATLETA CASCADE CONSTRAINTS;