CREATE TABLE Torneio(
    codTorneio NUMBER NOT NULL,
    nome CHAR(25) NOT NULL,
    grauDificuldade NUMBER NOT NULL,
    status CHAR(11) NOT NULL
);
ALTER TABLE Torneio ADD CONSTRAINT PKTORNEIO PRIMARY KEY (codTorneio);
CREATE SEQUENCE codTorneio MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE Modalidade(
    codModalidade NUMBER NOT NULL AUTO_INCREMENT,
    nome CHAR(50) NOT NULL,
    sexo CHAR(9) NOT NULL
);
ALTER TABLE Modalidade ADD CONSTRAINT PKMODALIDADE PRIMARY KEY (codModalidade);
CREATE SEQUENCE codModalidade MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE Prova(
    codProva NUMBER NOT NULL,
    codTorneio NUMBER NOT NULL,
    codModalidade NUMBER NOT NULL
);
ALTER TABLE Prova ADD CONSTRAINT PKPROVA PRIMARY KEY (codProva);
ALTER TABLE Prova ADD CONSTRAINT FKPROVA_TORNEIO 
    FOREIGN KEY (codTorneio) REFERENCES Torneio (codTorneio);
ALTER TABLE Prova ADD CONSTRAINT FKPROVA_MODALIDADE 
    FOREIGN KEY (codModalidade) REFERENCES Modalidade (codModalidade);
CREATE SEQUENCE codProva MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE Serie(
    codSerie NUMBER NOT NULL,
    codProva NUMBER NOT NULL,
    etapa CHAR(13) NOT NULL,
    dataRealizacao DATE NOT NULL,
    status CHAR(10) NOT NULL
);
ALTER TABLE Serie ADD CONSTRAINT PKSERIE PRIMARY KEY (codSerie);
ALTER TABLE Serie ADD CONSTRAINT FKSERIE_PROVA 
    FOREIGN KEY (codProva) REFERENCES Prova (codProva);
CREATE SEQUENCE codSerie MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE Atleta (
    codAtleta NUMBER NOT NULL,
    cpf NUMBER NOT NULL,
    nome CHAR(50) NOT NULL,
    sexo CHAR(9) NOT NULL,
    dataNascimento DATE NOT NULL ,
    nacionalidadde CHAR(10) NOT NULL    
);
ALTER TABLE Atleta ADD CONSTRAINT PKATLETA PRIMARY KEY (codAtleta);
CREATE SEQUENCE codAtleta MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE SerieClassificacao(
    codSerie NUMBER NOT NULL,
    codAtleta NUMBER NOT NULL,
    marca NUMBER(3,5),
    colocacao NUMBER,
    statusClassificacaoAtleta CHAR(15) 
);
ALTER TABLE SerieClassificacao ADD CONSTRAINT FKSERIECLASSIFICACAO_SERIE 
    FOREIGN KEY (codSerie) REFERENCES Serie (codSerie);
ALTER TABLE SerieClassificacao ADD CONSTRAINT FKSERIECLASSIFICACAO_ATLETA 
    FOREIGN KEY (codAtleta) REFERENCES Atleta (codAtleta);
    
CREATE TABLE AtletaHistorico(
    codAtleta NUMBER NOT NULL,
    codTorneio NUMBER NOT NULL,
    codModalidade NUMBER NOT NULL,
    marca NUMBER(3,5) NOT NULL,
    colocacao NUMBER NOT NULL,
    nota NUMBER(3,5) NULL
);
ALTER TABLE AtletaHistorico ADD CONSTRAINT FKATLETAHISTORICO_ATLETA 
    FOREIGN KEY (codAtleta) REFERENCES Atleta (codAtleta);
ALTER TABLE AtletaHistorico ADD CONSTRAINT FKATLETAHISTORICO_TORNEIO 
    FOREIGN KEY (codTorneio) REFERENCES Torneio (codTorneio);
ALTER TABLE AtletaHistorico ADD CONSTRAINT FKATLETAHISTORICO_MODALIDADE 
    FOREIGN KEY (codModalidade) REFERENCES Modalidade (codModalidade);
    
CREATE TABLE ProvaInscritos(
    codProva NUMBER NOT NULL,
    codAtleta NUMBER NOT NULL
);
ALTER TABLE ProvaInscritos ADD CONSTRAINT FKPROVAINSCRITOS_PROVA
    FOREIGN KEY (codProva) REFERENCES Prova (codProva);
ALTER TABLE ProvaInscritos ADD CONSTRAINT FKPROVAINSCRITOS_ATLETA
    FOREIGN KEY (codAtleta) REFERENCES Atleta (codAtleta);

CREATE OR REPLACE TRIGGER CRIARMODALIDADE 
BEFORE INSERT ON MODALIDADE
FOR EACH ROW
BEGIN
 IF :NEW.CODMODALIDADE IS NULL 
    THEN
    SELECT CODMODALIDADE.NEXTVAL INTO :NEW.CODMODALIDADE
    FROM DUAL;
 END IF;
END;

CREATE OR REPLACE TRIGGER CRIARTORNEIO
BEFORE INSERT ON TORNEIO
FOR EACH ROW
BEGIN
 IF :NEW.CODTORNEIO IS NULL 
    THEN
    SELECT CODTORNEIO.NEXTVAL INTO :NEW.CODTORNEIO
    FROM DUAL;
 END IF;
END;

CREATE OR REPLACE TRIGGER CRIARPROVA 
BEFORE INSERT ON PROVA
FOR EACH ROW
BEGIN
 IF :NEW.CODPROVA IS NULL 
    THEN
    SELECT CODPROVA.NEXTVAL INTO :NEW.CODPROVA
    FROM DUAL;
 END IF;
END;

CREATE OR REPLACE TRIGGER CRIARSERIE
BEFORE INSERT ON SERIE
FOR EACH ROW
BEGIN
 IF :NEW.CODSERIE IS NULL 
    THEN
    SELECT CODSERIE.NEXTVAL INTO :NEW.CODSERIE
    FROM DUAL;
 END IF;
END;

CREATE OR REPLACE TRIGGER CRIARATLETA
BEFORE INSERT ON ATLETA
FOR EACH ROW
BEGIN
 IF :NEW.CODATLETA IS NULL 
    THEN
    SELECT CODATLETA.NEXTVAL INTO :NEW.CODATLETA
    FROM DUAL;
 END IF;
END;