CREATE TABLE Torneio(
    codTorneio NUMBER NOT NULL,
    nome VARCHAR2(50) NOT NULL,
    grauDificuldade NUMBER NOT NULL,
    status VARCHAR2(11) NOT NULL
);
ALTER TABLE Torneio ADD CONSTRAINT PKTORNEIO PRIMARY KEY (codTorneio);
CREATE SEQUENCE codTorneio MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE Modalidade(
    codModalidade NUMBER NOT NULL,
    nome VARCHAR2(50) NOT NULL,
    sexo VARCHAR2(9) NOT NULL
);
ALTER TABLE Modalidade ADD CONSTRAINT PKMODALIDADE PRIMARY KEY (codModalidade);
CREATE SEQUENCE codModalidade MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE Prova(
    codProva NUMBER NOT NULL,
    codTorneio NUMBER NOT NULL,
    codModalidade NUMBER NOT NULL,
    sexo VARCHAR2 NOT NULL
);
ALTER TABLE Prova ADD CONSTRAINT PKPROVA PRIMARY KEY (codProva);
ALTER TABLE Prova ADD CONSTRAINT FKPROVA_TORNEIO 
    FOREIGN KEY (codTorneio) REFERENCES Torneio (codTorneio);
ALTER TABLE Prova ADD CONSTRAINT FKPROVA_MODALIDADE 
    FOREIGN KEY (codModalidade) REFERENCES Modalidade (codModalidade);
CREATE SEQUENCE codProva MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE Serie(
    codSerie NUMBER NOT NULL,
    codProva NUMBER NOT NULL,
    etapa VARCHAR2(13) NOT NULL,
    data VARCHAR2(10) NOT NULL,
    hora VARCHAR2(5) NOT NULL,
    status VARCHAR2(10) NOT NULL
);
ALTER TABLE Serie ADD CONSTRAINT PKSERIE PRIMARY KEY (codSerie);
ALTER TABLE Serie ADD CONSTRAINT FKSERIE_PROVA 
    FOREIGN KEY (codProva) REFERENCES Prova (codProva);
CREATE SEQUENCE codSerie MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE Atleta (
    codAtleta NUMBER NOT NULL,
    cpf NUMBER NOT NULL,
    nome VARCHAR2(50) NOT NULL,
    sexo VARCHAR2(9) NOT NULL,
    dataNascimento VARCHAR2(10) NOT NULL ,
    nacionalidade VARCHAR2(10) NOT NULL    
);
ALTER TABLE Atleta ADD CONSTRAINT PKATLETA PRIMARY KEY (codAtleta);
CREATE SEQUENCE codAtleta MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE SerieClassificacao(
    codSerie NUMBER NOT NULL,
    codAtleta NUMBER NOT NULL,
    marca NUMBER(3,5),
    raiaParticipacao NUMBER,
    colocacao NUMBER,
    statusClassificacaoAtleta VARCHAR2(15) 
);
ALTER TABLE SerieClassificacao ADD CONSTRAINT FKSERIECLASSIFICACAO_SERIE 
    FOREIGN KEY (codSerie) REFERENCES Serie (codSerie);
ALTER TABLE SerieClassificacao ADD CONSTRAINT FKSERIECLASSIFICACAO_ATLETA 
    FOREIGN KEY (codAtleta) REFERENCES Atleta (codAtleta);
    
CREATE TABLE AtletaHistorico(
    codAtleta NUMBER NOT NULL,
    codTorneio NUMBER NOT NULL,
    codModalidade NUMBER NOT NULL,
    marca NUMBER(3,5) NOT NULL,
    colocacao NUMBER NOT NULL,
    nota NUMBER(3,5) NULL
);
ALTER TABLE AtletaHistorico ADD CONSTRAINT FKATLETAHISTORICO_ATLETA 
    FOREIGN KEY (codAtleta) REFERENCES Atleta (codAtleta);
ALTER TABLE AtletaHistorico ADD CONSTRAINT FKATLETAHISTORICO_TORNEIO 
    FOREIGN KEY (codTorneio) REFERENCES Torneio (codTorneio);
ALTER TABLE AtletaHistorico ADD CONSTRAINT FKATLETAHISTORICO_MODALIDADE 
    FOREIGN KEY (codModalidade) REFERENCES Modalidade (codModalidade);
    
CREATE TABLE ProvaInscritos(
    codProva NUMBER NOT NULL,
    codAtleta NUMBER NOT NULL
);
ALTER TABLE ProvaInscritos ADD CONSTRAINT FKPROVAINSCRITOS_PROVA
    FOREIGN KEY (codProva) REFERENCES Prova (codProva);
ALTER TABLE ProvaInscritos ADD CONSTRAINT FKPROVAINSCRITOS_ATLETA
    FOREIGN KEY (codAtleta) REFERENCES Atleta (codAtleta);