create or replace TRIGGER CALCULA_NOTA_ESPECIFICA
AFTER INSERT ON ATLETAHISTORICO
FOR EACH ROW 
DECLARE DIFICULDADE NUMBER;
BEGIN
  SELECT T.GRAUDIFICULDADE INTO DIFICULDADE
    FROM TORNEIO T 
    WHERE T.CODTORNEIO = :NEW.CODTORNEIO;
  
  IF DIFICULDADE > 0
  THEN 
    UPDATE ATLETAHISTORICO SET NOTA = 1/:NEW.COLOCACAO * DIFICULDADE;
  END IF;
END CALCULA_NOTA_ESPECIFICA;