CREATE OR REPLACE TRIGGER CRIARTORNEIO 
BEFORE INSERT ON TORNEIO
FOR EACH ROW
BEGIN
 IF :NEW.CODTORNEIO IS NULL 
    THEN
    SELECT CODTORNEIO.NEXTVAL INTO :NEW.CODTORNEIO
    FROM DUAL;
 END IF;
END;
/
ALTER TRIGGER CRIARTORNEIO ENABLE;
