CREATE OR REPLACE TRIGGER CRIARPROVA 
BEFORE INSERT ON PROVA
FOR EACH ROW
BEGIN
 IF :NEW.CODPROVA IS NULL 
    THEN
    SELECT CODPROVA.NEXTVAL INTO :NEW.CODPROVA
    FROM DUAL;
 END IF;
END;
/
ALTER TRIGGER CRIARPROVA ENABLE;
