CREATE OR REPLACE TRIGGER CRIARATLETA
BEFORE INSERT ON ATLETA
FOR EACH ROW
BEGIN
 IF :NEW.CODATLETA IS NULL 
    THEN
    SELECT CODATLETA.NEXTVAL INTO :NEW.CODATLETA
    FROM DUAL;
 END IF;
END;
/
ALTER TRIGGER CRIARATLETA ENABLE;
