CREATE OR REPLACE TRIGGER CRIARSERIE 
BEFORE INSERT ON SERIE
FOR EACH ROW
BEGIN
 IF :NEW.CODSERIE IS NULL 
    THEN
    SELECT CODSERIE.NEXTVAL INTO :NEW.CODSERIE
    FROM DUAL;
 END IF;
END;
/
ALTER TRIGGER CRIARSERIE ENABLE;
