create or replace FUNCTION CALCULA_NOTA_GERAL(CODMODALIDADE_ NUMBER, CODATLETA_ NUMBER)
RETURN NUMBER
AS V_RETORNO NUMBER;
BEGIN
  SELECT SUM(AH.NOTA) INTO V_RETORNO
    FROM ATLETAHISTORICO AH
    WHERE AH.CODMODALIDADE = CODMODALIDADE_
    AND AH.CODATLETA = CODATLETA_; 
  RETURN V_RETORNO;
END CALCULA_NOTA_GERAL;